### ISSUE TITLE
Feature Request List

### ISSUE THREAD

**Issue by TimKroeger13** [Machriam/TheCardEditor#1]
# Feature Request List:

- [x] #2
  - so könnte man für einen kartenset mithilfe eines Folder Pickers z.B der ordner "V:\Brettspiele\Timgammen_aktuell\Karten\Cards_V1_02_04" Auswählen
  - Die eigentlich Bilder hätten dann nur die Reference "act_001_E_Sandsturm.png"
  - Es ist schon praktisch, dann kann ich auch Ordner leichter tauschen ohne alles umzubennen wenn ich andere Layouts testen will.

- [x] Möglichkeit haben ein Bild zu adden
  - Drag and drop um die file location zu adden --> Suchfunktion mit Dropdown

- [x] Liste alle Elemente auf einer Karte
  - Vielleicht wären zwei Listen praktischer. Eine die nur text Felder enthält und eine die nur Bilder enthält
  - Wenn ein Element in der Liste angeklickt wird ist es für den Editor ausgewählt

- [x] Der Text eines Textfelder wird ebenfalls im Text input Feld für die Erstellung angezeigt.
  - Wird Text im input Feld geändert soll auch der Text im Inputfeld geändert werden

- [x] Sollte man ungespeichte änderungen verwerfen (Das Fenster schließen) soll einen eine Warnung angezeigt werden ob man dies wirklich will

- [x] Feature einbauen Karten als Template zu speichern

- [x] Feature einbauen Karten Tempaltes einzualden
  - Das sollte nur möglich sein wenn man eine neuen Karte erstellt. Da sollte man angeben ob man ein Template benutzen will oder nicht.

- [x] Es wäre nett wen teamples eine Ordner struktur zulassen und nicht alle in einen liegen. Das würde helfen sich bei der vielzahl besser zurechtzufinden.

- [x] Button um eine Karte zu löschen (Ist warscheinlich schon eingebaut)
  - Vielleicht sollte es hier auch eine Warnung geben.

- [x] Wenn ein neues Text Feld erstellt wird, sollte es auf der größe der derzeit angegebenden Schriftgröße erstellt werden

**Comment by TimKroeger13** [comment]
- Feld hinzufügen wo man den Zeilenabstand für ein Textfeld ändern kann
- Möglichkeit einbauen alle Bilder zu locken
   - Ich will Textfelder hin und her bewegen können ohne ausversehen daneben zu klicken und dann das Hintergrundbild zu verrücken.
   - Und ja es ist redundant da man sie auch in der Liste auswählen könnte, aber das ist nicht so fluiede.

**Comment by Machriam** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GRUSEL~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GRUSEL~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



1 | Soul | Movement | Visiting the Dead | Move a Player to a other Player that is Dead. | Draw 1 extra Soul Cards
-- | -- | -- | -- | -- | --
2 | Soul | Damage | Soul Swap | Choose a Player: Swap your Damage dice with a Damage dice of the chosen   Player. | Taunt+2
3 | Soul | Defense | Skin share | Choose a Player: Swap your Defense dice with a Defense dice of the chosen   Player. | Defense+1
4 | Soul | Defense | Hardened soul | Choose a Player: He gets double the the defense of his defense dice. | Defense+1
5 | Soul | Defense | Soul Shield | Choose a Player: You can that player get defense+3. | Defense+1
6 | Soul | Defense | Soulmate | Choose A Player:  Give that Player   Defense+4 | Defense+1
7 | Soul | Blank | Blank |   |  
8 | Soul | Other | Hiking blessing | Choose a Player: Swap your Move dice   with a Move dice of the chosen Player.
9 | Soul | Other | Soul Sharing | Your dice also count these rounds as   the dice of a chosen player.
10 | Soul | Other | New Fate | Re-roll all your dice
  |   |   |   |   |  
1 | Frost | Blank | Blank |   |  
2 | Frost | Damage | Frostbolt | Range4. +10 seconds Deal DD-2. | Taunt+1
3 | Frost | Damage | Blizzard | Range4. +20 seconds. Dead DD+1 Damage. | Taunt+1 All player have movement-1.
4 | Frost | Defense | Permafrost | Focus +10 seconds Choose a Player:   Freez him. He can’t play Cards anymore. He has Defense+6
5 | Frost | Defense | Brain freeze | Focus Choose a Player: He has DD +2.   He can’t play Rush Cards this turn anymore.
6 | Frost | Defense | Ice Wall | +10 Seconds | The Boss move 1 less vertical and horizontal field.
7 | Frost | Defense | Frost armor | Gain Defense+5
8 | Frost | Defense | Create Igloo | All player on your field gain   defense+3.
9 | Frost | Movement | Frozen Path | Focus +20 Seconds Double all player movement. They have to walk there   full movement. | All player have movement-1.
10 | Frost | Other | Chill | +20 Seconds | +20 Seconds
  |   |   |   |   |  
1 | Fire | Blank | Blank |   |  
2 | Fire | Damage | Pyroblast | Focus, Range2 -20 Seconds Dead DD+2 damage. Get “Rage”. | Taunt+1 Damage-1
3 | Fire | Damage | Wildfire | Focus,Range0. Dead DD damage. Defense+2 | Taunt+1 Damage-1
4 | Fire | Damage | Fireball | Focus, Range2. -10 Seconds Dead DD+1 damage. | Taunt+1 Damage-1
5 | Fire | Damage | Ignite | Focus Range4. -10 Seconds Dead DD damage. | Taunt+1 Damage-1
6 | Fire | Damage | Flamestrike | Focus. Reach1. -10 Seconds Dead DD+2 damage. | Taunt+1 Damage-1
7 | Fire | Defense | Flamewall | Focus. -20 Seconds Gein Defense +5
8 | Fire | Movement | Burning Steps | Move Movement Fields. Deal your DD   every field passed to others. Including the target field.
9 | Fire | Movement | Fire kick | Rush Move a Player 2 Field away from   you.
  |   |   |   |   |  
10 | Fire | Other | Hot Streak | Rush. -10 Seconds You next Spell deals Double Damage. | Taunt+1 Damage-1
1 | Illusion | Blank | Blank |   |  
2 | Illusion | Damage | Copy Cat | Copy ally played damage spell
3 | Illusion | Damage | Motivated | Range2. Choose a player. That player   has Damage+2
4 | Illusion | Defense | Mirror shield | Range2. Choose a player. That player   has Defense+3
5 | Illusion | Defense | The will to survive | Choose a player with the highest   taunt: He gets Defense+5
6 | Illusion | Movement | Fear | Choose a other player: He get   Movement+2 when he run away from the Boss.
7 | Illusion | Movement | Teleport | Choose a Player: Teleport a player to a other player. | Movement-1
8 | Illusion | Other | Mirror image | Choose a player: That player looses   2 Taunt
9 | Illusion | Other | Invisibility | Choose a player: That looses player   3 Taunt.
10 | Illusion | Other | Lullaby | Range2, Focus. Choose a player: He   can’t play cards anymore. He heals 4 Health.
  |   |   |   |   |  
1 | Violence | Blank | Blank |   |  
2 | Violence | Damage | Kick | Range1 Kick the Boss 1 Field away from you. Deal DD damage | Heal 1 Health
3 | Violence | Damage | Punch | Range0. DD+2 | Heal 1 Health
4 | Violence | Damage | Whirlwind | Range1. Deal DD+1 to all characters   in Range.
5 | Violence | Damage | Sonic Wave | Deal DD-2 | The Boss deal 1 Less damage
6 | Violence | Damage | All in | Range0. DD+3 | Heal 1 Health Defense-2
7 | Violence | Defense | All out | Defense+6 | Heal 1 Health Damage-2
8 | Violence | Defense | Protect | Range0. Choose a player: Add you defense dice to the defense of that   player. | Heal 1 Health
9 | Violence | Movement | Charge | Move MD+1 Deal DD damage to all character on the target Field. | Heal 1 Health
10 | Violence | Other | War cry | Taunt+2 “Rage” All player get Damage+1. | Heal 1 Health



</body>

</html>

**Comment by TimKroeger13** [comment]
- [ ] When rotating an item it should be possible to rotate it in fix degrees. I recommend that when I hold the shift key while rotating an item it only rotated in 11.25° steps.
- [ ] I need a options that pictures gets multiplied on pictures below them (multiplie filter function)
- [ ] Error: It is possible to open the "Card Editor" / "Text editor" and "Picture Manager" while no card set is selected.
- [ ] Its possible to click "Text Editor" and "Picture Manager" while editing a card. This causes the pictures to get lost and throws an error
- [ ] In Home: Double clicking Card set should open the "Card Editor"
- [ ] In Home: Select Card Set clicking "Select Card Set and Game" should also open the editor
- [ ] - A Button is needed to rescale pictures to there resoultion there were loaded in. There orginal resoulution. (Maybe use the clear button also for this)
-> The same button also should reverse the rotation of a picture to his zero rotation
- [ ]  Pictures should also be poissible to be scaled after the nearest neighbor formula for pixel.
- [ ] Cards export to an other cardset
- [ ] Template export to an other cardset
- [ ] When clicking new card and the Select Template windows open its not possible to leave the window. Is takes me hostage
- [ ] There is no way to delete picture folder references in the "Picture Manager"
- [ ] Deleting a Game and then creating on with the same name causes an error
- [ ] In Home: Rename Update Game button to update name
- [ ] When creating a new game it still has the same references in the "Picture Manager" as the other games
- [ ] Entf as a shortcut for deleting the selected Item (Like the minus button)
- [ ] Error: When importing pictures in the picture manager and then changing the name of them or delete the original picture the reference in the picture manager does not get updated. Then its sill possible to import the not existing image into a Card.
-> After renaming the picture and then importing the picture folder again, both the false and new image are listed. 
- [ ] That a selected card is showed in the foreground is missleading, because it doesen't show how the card really looks like.
-> This also stays when closing and re opening the Card! This is not good
-> Selected items should not be moved into the foreground. The order Showed is the given state that defines a card.
- [ ] False ordering of Pictures: When you have 2 images, selecting the bottom one and moving it up it goes into the background what makes no sense. Because then the top image is in the Background.
- [ ] Double Clicking a Card in the "Card Editor" should open it as an edit.

## Extra Features

- [ ] When clicking a picture in the picture manager you get a preview
- [ ] When nothing got change in a card, then there should be no warning when closing the editor.
- [ ] Invisible Text field Button
- [ ] The Error for trying to delete a game while it still contains card sets is cryptic. You can't sell the software this way^^
